### ISSUE TITLE
Github token is missing when adding a repo

### ISSUE THREAD

**Issue by juampi92** [saeghe/saeghe#9]
**Describe the bug**
The command `saeghe add git@github.com:symfony/routing.git` crashes when trying to install a new package. "Bad credentials" is retuned from github.

I tried using `ssh` and using `https`, both give the same error.

**Expected behavior**
A successful installation.

**Screenshots**
```bash
$ saeghe add git@github.com:bramus/router.git

PHP Warning:  Undefined array key 0 in /Users/juanpablo/.saeghe/saeghe/Source/Git/GitHub.php on line 90
PHP Stack trace:
PHP   1. {main}() /Users/juanpablo/.saeghe/saeghe/saeghe:0
PHP   2. Saeghe\Saeghe\Commands\Add\run($project = class Saeghe\Saeghe\Project { public Saeghe\Saeghe\Path $buildRoot = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php/builds/development' }; public Saeghe\Saeghe\Path $root = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php' }; public string $environment = 'development'; public Saeghe\Saeghe\Path $configFilePath = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php/saeghe.config.json' }; public Saeghe\Saeghe\Path $configLockFilePath = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php/saeghe.config-lock.json' }; public Saeghe\Saeghe\Path $credentialsPath = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/.saeghe/saeghe/credentials.json' } }) /Users/juanpablo/.saeghe/saeghe/saeghe:59
PHP   3. Saeghe\Saeghe\Commands\Add\add($project = class Saeghe\Saeghe\Project { public Saeghe\Saeghe\Path $buildRoot = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php/builds/development' }; public Saeghe\Saeghe\Path $root = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php' }; public string $environment = 'development'; public Saeghe\Saeghe\Path $configFilePath = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php/saeghe.config.json' }; public Saeghe\Saeghe\Path $configLockFilePath = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/Projects/saeghe-experiments/next-php/saeghe.config-lock.json' }; public Saeghe\Saeghe\Path $credentialsPath = class Saeghe\Saeghe\Path { private string $string = '/Users/juanpablo/.saeghe/saeghe/credentials.json' } }, $config = class Saeghe\Saeghe\Config { public array $map = ['Application' => 'app', 'Next' => 'nextphp']; public array $entryPoints = [0 => 'public/index.php']; public array $excludes = []; public array $executables = []; public string $packagesDirectory = 'Packages'; public array $packages = [] }, $package = class Saeghe\Saeghe\Package { public string $version = 'development'; public string $hash = *uninitialized*; public string $owner = 'bramus'; public string $repo = 'router' }, $packageUrl = 'git@github.com:bramus/router.git') /Users/juanpablo/.saeghe/saeghe/Source/Commands/Add.php:45
PHP   4. Saeghe\Saeghe\Git\Repository->detectHash() /Users/juanpablo/.saeghe/saeghe/Source/Commands/Add.php:55
PHP   5. Saeghe\Saeghe\Providers\GitHub\find_latest_commit_hash($owner = 'bramus', $repo = 'router') /Users/juanpablo/.saeghe/saeghe/Source/Git/Repository.php:71
```

**Environment:**
 - OS: Mac
 - OS Version: Monterey 12.6
 - PHP Version PHP 8.1.11
 - Version `saeghe -v` or `saeghe version` doesn't exist, but I have the latest version.

**Additional context**
I added a var_dump on the Github error, and the json returns `Bad credentials`. I realised that the method `github_token()` returns an empty string, since I don't have a `GITHUB_TOKEN` env.

I might have missed something in the installation, but maybe it would be great to customize this message error with some instructions on how to properly install the github_token (or maybe not needing to use one)

**Comment by MortezaPoussaneh** [comment]
Thank you @juampi92 , yes, you need to have a GitHub token. Unfortunately, I didn't have time to update the website.
I will update the website as soon as possible.
If you used the installer, there would be a `credential.json` file in `~/.saeghe` that you can edit and add your GitHub token.
There is also a `credential` command that you can use. Run `saeghe credential github.com your-github-access-token` and it gets added to the credentials file.

**Comment by MortezaPoussaneh** [comment]
Use [https://saeghe.com/documentations/credential-command](https://saeghe.com/documentations/credential-command)

**Comment by jawira** [comment]
I had the same issue, it would be nice if credentials could be checked and then return a nice message like "Credentials are required, run saeghe credential", for example.

Same if you run Saeghe in PHP 7.4, you get `PHP Parse error:  syntax error, unexpected '=>'`, it would be nice to have a more helpful message like "PHP 7.4 not supported, update to PHP 8" or something like that.

**Comment by MortezaPoussaneh** [comment]
Installation upgraded. It does not install Saeghe if you don't have PHP >= 8.
I also added error handling for invalid tokens.
I hope you catch the error faster now.
